### PR TITLE
Add dbus-core to marshalling benchmarks

### PR DESCRIPTION
**Pull request by tmiasko**

### CODE REVIEW

**Comment by KillingSpark** [comment]
Thanks for contributing this. Sorry for delaying this for so long!

**Comment by KillingSpark** [comment]
I had a short look at your library. It's a cool implementation, especially having the encode_array in the encode trait never occurred to me as useful but it absolutely is, to make optimization more transparent. 

Out of interest, do have a good way to support filedescriptors similar to libdbus? In rustbus the library user has to map fds and indexes himself, which is just annoying and destroys ease of use.

**Comment by tmiasko** [comment]
For encode_array the long term goal would be to replace it with specialization, once it is stable. But yeah, it would hide the fact that optimization takes place.

So far I didn't need to transfer file descriptors, so that part needs a design work. The implementation that merely returns fd indexes would be trivial, but if file descriptors were to be available to the decoder it could return them as well.

**Comment by KillingSpark** [comment]
I thought about introducing an Encoding/Decoding-Context struct that would collect FDs, I hope I can do this without changing the public API. Libdbus just passes a pointer to the whole message down the en-/decoding codepath to fetch/append fds, which I would try to emulate with that. I'd be interested if you come up with a more elegant approach to this problem.

**Pull request merged**
