### PR TITLE
Add dbus-pure

### PR DESCRIPTION
**Pull request by Arnavion**
Assuming I've written it correctly, here's the result of running `cargo bench`. I didn't update the table in the README because I assume you would want those to be based on your machine.

FWIW, I get +/- 10% just by running the benches again and again, with `p = 0.00 < 0.05` at that. I don't know much about criterion, but if it really is doing only 100 measurements, maybe it should be configured to do more.

<details>
<summary>Bench results</summary>

```
marshal_rustbus         time:   [47.079 us 47.205 us 47.346 us]
Found 7 outliers among 100 measurements (7.00%)
  3 (3.00%) high mild
  4 (4.00%) high severe

marshal_dbusrs          time:   [376.83 us 377.93 us 379.15 us]
Found 10 outliers among 100 measurements (10.00%)
  7 (7.00%) high mild
  3 (3.00%) high severe

marshal_dbus_bytestream time:   [33.211 us 33.300 us 33.400 us]
Found 7 outliers among 100 measurements (7.00%)
  4 (4.00%) high mild
  3 (3.00%) high severe

marshal_dbus_message_parser
                        time:   [87.333 us 87.733 us 88.205 us]
Found 10 outliers among 100 measurements (10.00%)
  8 (8.00%) high mild
  2 (2.00%) high severe

marshal_dbus_pure       time:   [45.458 us 45.604 us 45.776 us]
Found 5 outliers among 100 measurements (5.00%)
  1 (1.00%) high mild
  4 (4.00%) high severe

marshal_zvariant        time:   [42.221 us 42.309 us 42.404 us]
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high mild

send_rustbus            time:   [408.75 us 423.79 us 440.77 us]
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high mild

send_dbusrs             time:   [1.0313 ms 1.0729 ms 1.1135 ms]

send_dbus_bytestream    time:   [346.25 us 353.08 us 360.69 us]
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) high mild
  3 (3.00%) high severe

send_dbus_pure          time:   [343.58 us 351.77 us 360.64 us]
Found 5 outliers among 100 measurements (5.00%)
  4 (4.00%) high mild
  1 (1.00%) high severe
```
</details>

### CODE REVIEW

**Comment by KillingSpark** [comment]
Thanks!
Yes I have been seeing this behavior too, I will look into how to tell criterion to use more samples.

**Comment by KillingSpark** [comment]
I just saw that in your runs dbus-pure ist slightly faster than rustbus, but in my measurements it's reversed. Would you mind sharing what hardware you use?

**Comment by Arnavion** [comment]
The report in the OP was generated on nightly, `rustc 1.43.0-nightly (6fd8798f4 2020-02-25)` to be precise. I do see it's just slightly slower in the marshal test if I use stable (`rustc 1.41.0 (5e1a79984 2020-01-27)` to be precise), though it's still faster in the send test, though the difference is less than it was on nightly:

```
marshal_rustbus         time:   [47.540 us 47.756 us 48.008 us]
marshal_dbus_pure       time:   [48.712 us 48.960 us 49.263 us]

send_rustbus            time:   [389.15 us 405.87 us 423.83 us]
send_dbus_pure          time:   [361.89 us 375.29 us 389.66 us]
```

For completeness, I have a Threadripper 2920X - 12 cores, 24 threads, max ~4.3 GHz on one thread, running in NUMA mode - (though the benches only use one thread of course), ~64 GiB DDR4 2666 ECC RAM, and the regular `x86_64-unknown-linux-gnu` target.

---

BTW, looks like you released rustbus 0.1.1, but it's not semver compatible with 0.1.0 because of the new lifetime parameters. So anything that depended on `rustbus = "0.1.0"`, including this repo, will break. (I had to manually `cargo update -p rustbus --precise 0.1.0` to downgrade after I previously `git clean`'d the working `Cargo.lock`)

---

Also, with the ability to use borrows like you added in rustbus 0.1.1 (though it's not perfect; you ask for `&Vec` in some cases instead of `&[]`, so it still needs allocation), both of our crates would benefit from using borrows instead of allocating `Box`es and `Vec`s which just get used within the benchmark anyway. `dbus-pure` uses `Cow` extensively because most values only need to be converted to `Variant` for a short duration.

But currently two things prevent that:

1. The message is returned from a `make_` function, so it cannot contain borrows from anything inside the function.

1. The `marshal_` test returns the message, so the message cannot contain borrows from anything inside the benchmark function either.

(1) can be solved by inlining the `make_` function into the `marshal_` and `send_` tests. It could work to make it a macro `macro_rules! make_foo_message { ($message:ident) => { let $message = ... }; }` if you still want it to be shared between the two test functions.

(2) can be solved by returning the encoded buffer instead of the message.

**Comment by KillingSpark** [comment]
Tanks for the detailed answer!

> BTW, looks like you released rustbus 0.1.1, but it's not semver compatible with 0.1.0 because of the new lifetime parameters. So anything that depended on rustbus = "0.1.0", including this repo, will break. (I had to manually cargo update -p rustbus --precise 0.1.0 to downgrade after I previously git clean'd the working Cargo.lock)

Damn I thought semver 0.1.x was somewhat allowing willy nilly breakage, I didn't know it could cause that kind of trouble.

> (1) can be solved by inlining the make_ function into the marshal_ and send_ tests. It could work to make it a macro macro_rules! make_foo_message { ($message:ident) => { let $message = ... }; } if you still want it to be shared between the two test functions.
(2) can be solved by returning the encoded buffer instead of the message.

I was going to do something like this, to showcase how marshalling / message creation can benefit from borrowing strings instead of owning them.

**Comment by Arnavion** [comment]
The semver spec does indeed say no compatibility rules apply to 0.x, but cargo specifically treats 0.x.y just like x.y, ie 0.1.0 -> 0.1.1 is a "minor version upgrade" just like 1.0 -> 1.1 would be. So just like `foo = "1.0"` allows foo@1.1.0, in the same way `foo = "0.1.0"` allows foo@0.1.1

**Comment by KillingSpark** [comment]
I see. The next release should be a 0.2.0 then.

I fixed the two points and it gave some of the libraries a performance boost to be able to use borrowed strings, if you are interested :)

**Pull request merged**
