### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by zeenix**
I wanted to borrow some of the code for my own benchmarking but I can't do so legally w/o knowing the exact license.

### CODE REVIEW

**Comment by KillingSpark** [comment]
I am not sure how common it is to make PRs with licenses. I think it is not right (and maybe even illegal) to just add a license I did not agree to on your own PUBLIC fork, and by that creating a false allowance for others to copy and use as they wish. Also, just proposing one license without at least saying which one you chose, and giving reasons for why you chose MIT and not some other (besides 'I wanna copy some code', because that would work with most licenses) is just not nice.

I'd like you to delete this branch with the license you added. I will add a license to this repo myself.

**Comment by zeenix** [comment]
I'm not sure why you're upset. This PR was a suggestion. I used the "add license" button offered by GH ([as is commonly done](https://choosealicense.com/no-permission/)) and chose the most common license used in the Rust world.

Of course it's up to you which license you choose in the end.

IANAL but If we talk strictly legal, I think:

1. When contributors forked and modified the code in your repo (without any license explicitly mentioned), they all broke the law.

2. You might need permission from all contributors for choosing a license. I'm not sure about this one so seek legal advice from someone who knows better.

In any case, I was only trying to help. There is no reason for you to be so upset and rude about this. If you care so much, please add license to your software in the future.

**Comment by KillingSpark** [comment]
From your link (emphasis mine):
> When **you** make a creative work (which includes code), the work is under exclusive copyright by default. Unless **you** include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

What they suggest is: 
>Ask the maintainers nicely to add a license. Unless the software includes strong indications to the contrary, lack of a license is probably an oversight. If the software is hosted on a site like GitHub, open an issue requesting a license and include a link to this site. If you’re bold and it’s fairly obvious what license is most appropriate, open a pull request to add a license – see “suggest this license” in the sidebar of the page for each license on this site (e.g., MIT).

You are right, that for rust MIT is mostly used, but Apache2.0 is also very common. For a repo like this a public-domain or creative-commons would also be appropriate because it really is not that much code, it's just a very small comparison, which I made so anyone can have a bit of guidance on what to choose, between all the different dbus impls out there. I think I am in the right to be upset about a "bold move", which from my point of view has no clear reasons to be taken.

You are correct that this repo currently contains work by more than one person, without having had a license. But you are definitely not the one to make a new license IN MY NAME.
> MIT License
>
>Copyright (c) 2020 Moritz Borcherding
>
>Permission is hereby granted, free of charge, to any person obtaining a copy
>of this software and associated documentation files (the "Software"), to deal
>.....

I am upset because you created a potentially legally relevant document in my name without my consent. You are correct that I might not be able to create a license myself at this point without the consent of all contributors (which is why I was hesitant to include one after my first response). Having no license means we are all working with a somewhat implicit agreement that what is going on is ok-ish, there is no judge if there is no plaintiff. If anyone of the contributors is going to fight that, I'll probably just take this repo down, it's not worth the hassle honestly.

I am sorry, this is so negative in tone, and I apologise for any rudeness but I was very taken aback by this PR. You are of course correct that I should have taken more care to include a license from the get-go.

**Comment by KillingSpark** [comment]
As a sidenote, license for the whole repo aside, I'll of of course grant you permission to copy any of my code from this repo for your own benchmarks.

**Comment by zeenix** [comment]
I think you're ignoring the fact that I just used the Github's own UI and the license file was automatically generated with your name once I chose a license. This is all automated and I didn't assume anything.

All I wanted was to save you some time by choosing the license for my "suggestion". You can (and you did) of course say "no" and do what you think is best. So no, I really don't see why you'd be upset about a PR. It's not like I have any intention of distributing my branch (which i deleted immediately after seeing your response btw) that was automatically created by Github.

> What they suggest is:
> 
> > Ask the maintainers nicely to add a license. Unless the software includes strong indications to the contrary, lack of a license is probably an oversight. If the software is hosted on a site like GitHub, open an issue requesting a license and include a link to this site. If you’re bold and it’s fairly obvious what license is most appropriate, open a pull request to add a license – see “suggest this license” in the sidebar of the page for each license on this site (e.g., MIT).

Exactly! I did the last one cause I wanted to **potentially** save **your** time.

**Comment by zeenix** [comment]
> As a sidenote, license for the whole repo aside, I'll of of course grant you permission to copy any of my code from this repo for your own benchmarks.

Thanks.

**Pull request closed without merging**
